image_dir: "/cluster/home/plibera/images"
output_root: "/cluster/home/plibera/outputs/preds"
model_path: "/root/catkin_ws/src/self_supervised_segmentation/models/stego_cocostuff27_vit_base_5_cluster_linear_fine_tuning.ckpt"
# model_path: "/root/catkin_ws/src/self_supervised_segmentation/models/FF_training_200.ckpt"
# model_path: "/root/catkin_ws/src/self_supervised_segmentation/models/cityscapes_vit_base_1.ckpt"
experiment_name: "forest_youtube_val"
resolution: 320

# Loader params
batch_size: 8
num_workers: 24

run_crf: True